<?php
// $Id:nlg-systemerror-form.tpl.php $

/**
  * nlg-systemerror-form template 
  * @file
  * nlg-systemerror-form.tpl.php 
  * @package
  * sfsu.portlet.systemerror.portlets.theme
  *
  * The template for nlg-systemerror-form Template.
  */
?>

<div id="nlg_contents" class="leftalign">
  <p>
    <span style="font-weight: bold; font-size: 12pt; font-color: #ff0000;">Nagios Looking Glass Error Report</span>
  </p>
  <p>Sorry for the inconvenience, but Nagios Looking Glass could not retrieve the page you asked for.</p>
  <p>The error message below might hold more clues for the site administrator:</p>
  <p class ="red">
    <?php //TODO: error message [[ERROR_TEXT]] ?>
  </p>
  <p>Generated by Nagios Looking Glass at <?php //TODO: error time [[ERROR_TIME]] ?></p>
</div>
<div class="clearfloat"></div>

